package web

import (
	"embed"
	"io/fs"
	"mime"
	"net/http"
	"path"
	"strings"
)

// dist is generated by Vite before the release Go binary is built.
//
//go:embed dist/*
var dist embed.FS

func Handler() http.Handler {
	root, err := fs.Sub(dist, "dist")
	if err != nil { panic(err) }
	files := http.FS(root)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet && r.Method != http.MethodHead {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		requested := strings.TrimPrefix(path.Clean(r.URL.Path), "/")
		if requested == "." || requested == "" { requested = "index.html" }
		if info, err := fs.Stat(root, requested); err == nil && !info.IsDir() {
			serveFile(w, r, files, requested)
			return
		}
		serveFile(w, r, files, "index.html")
	})
}

func serveFile(w http.ResponseWriter, r *http.Request, files http.FileSystem, name string) {
	file, err := files.Open(name)
	if err != nil { http.NotFound(w, r); return }
	defer file.Close()
	info, err := file.Stat()
	if err != nil { http.NotFound(w, r); return }
	if ct := mime.TypeByExtension(path.Ext(name)); ct != "" { w.Header().Set("Content-Type", ct) }
	if strings.HasPrefix(name, "assets/") {
		w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
	} else {
		w.Header().Set("Cache-Control", "no-cache")
	}
	http.ServeContent(w, r, name, info.ModTime(), file)
}
