import { A, Route, Router, useNavigate, useSearchParams } from "@solidjs/router";
import { For, Show, createSignal } from "solid-js";
import * as stylex from "@stylexjs/stylex";
import { api, type Simulation } from "./api";
import { colors, s } from "./styles";

export function App(){return <div {...stylex.props(s.global)}><Router><Route path="/" component={Root}/><Route path="/game" component={GameHome}/><Route path="/login" component={Login}/><Route path="/login/verify" component={Verify}/><Route path="/game/:id" component={GameHome}/></Router></div>}
function isGameHost(){return location.hostname.startsWith("game.")}
function Root(){return isGameHost()?<GameHome/>:<Marketing/>}
function Nav(){return <nav {...stylex.props(s.nav)}><A href="/" {...stylex.props(s.brand)}>VUTADEX</A><div {...stylex.props(s.links)}><a href="https://vutadex.com" {...stylex.props(s.link)}>About</a><a href="https://game.vutadex.com" {...stylex.props(s.button)}>Play</a></div></nav>}
function Marketing(){return <><Nav/><main><section {...stylex.props(s.hero)}><div><div {...stylex.props(s.kicker)}>THE FOOTBALL UNIVERSE YOU CONTROL</div><h1 {...stylex.props(s.h1)}>Build it. Call it. Play it.</h1><p {...stylex.props(s.lead)}>Run the franchise as GM, call every snap as coach, and eventually take direct control on a live X/O field. Every season becomes permanent history in the Dex.</p><div {...stylex.props(s.actions)}><a href="https://game.vutadex.com" {...stylex.props(s.button)}>Enter VutaDex</a><a href="#modes" {...stylex.props(s.button,s.ghost)}>How it works</a></div></div><XOField/></section><section id="modes" {...stylex.props(s.section)}><div {...stylex.props(s.three)}><Mode title="GM" body="Scout, draft, trade, sign and construct the organization."/><Mode title="COACH" body="Choose personnel, formations, concepts, audibles and situational calls."/><Mode title="PLAYER" body="Take direct control after the snap as the real-time engine grows."/></div></section></main></>}
function Mode(p:{title:string;body:string}){return <article {...stylex.props(s.card)}><div {...stylex.props(s.kicker)}>{p.title}</div><h2>{p.title} MODE</h2><p {...stylex.props(s.muted)}>{p.body}</p></article>}
function XOField(){const xs=[[18,75],[31,75],[43,75],[50,75],[57,75],[69,75],[82,75],[50,83],[36,88],[64,88],[50,93]];const os=[[18,35],[31,35],[43,35],[50,35],[57,35],[69,35],[82,35],[30,25],[50,24],[70,25],[50,14]];return <div {...stylex.props(s.card)}><div {...stylex.props(s.field)}><For each={[10,20,30,40,50,60,70,80,90]}>{y=><div {...stylex.props(s.yard)} style={{top:`${y}%`}}/>}</For><For each={xs}>{p=><div {...stylex.props(s.token,s.x)} style={{left:`${p[0]}%`,top:`${p[1]}%`}}>X</div>}</For><For each={os}>{p=><div {...stylex.props(s.token,s.o)} style={{left:`${p[0]}%`,top:`${p[1]}%`}}>O</div>}</For></div></div>}
function GameHome(){const [sim,setSim]=createSignal<Simulation>();const [busy,setBusy]=createSignal(false);async function run(){setBusy(true);try{setSim(await api.simulate(Math.floor(Math.random()*1_000_000)))}finally{setBusy(false)}}return <><Nav/><main {...stylex.props(s.shell)}><div {...stylex.props(s.score)}><div><div {...stylex.props(s.team)}>TEAM X</div><div {...stylex.props(s.muted)}>Coach: You</div></div><div {...stylex.props(s.center)}><strong>{sim()?.state.homeScore ?? 0} — {sim()?.state.awayScore ?? 0}</strong><div {...stylex.props(s.muted)}>X/O COACH MODE</div></div><div style={{"text-align":"right"}}><div {...stylex.props(s.team)}>TEAM O</div><div {...stylex.props(s.muted)}>CPU</div></div></div><div {...stylex.props(s.grid)}><XOField/><aside {...stylex.props(s.card)}><div {...stylex.props(s.kicker)}>PLAY-BY-PLAY</div><p {...stylex.props(s.muted)}>The Go engine is deterministic and authoritative. This button runs a complete seeded game while M6 evolves into snap-by-snap coach mode.</p><button {...stylex.props(s.button)} disabled={busy()} onClick={run}>{busy()?"Simulating…":"Simulate game"}</button><div {...stylex.props(s.feed)} style={{"margin-top":"18px"}}><For each={sim()?.events.slice(-18).reverse() ?? []}>{e=><div {...stylex.props(s.play)}><strong>Q{e.quarter}</strong> {formatClock(e.clock)}<br/><span {...stylex.props(s.muted)}>{e.description}</span></div>}</For></div></aside></div></main></>}
function Login(){const[email,setEmail]=createSignal("");const[sent,setSent]=createSignal(false);async function submit(e:Event){e.preventDefault();await api.magicLink(email());setSent(true)}return <><Nav/><main {...stylex.props(s.section)}><div {...stylex.props(s.card)} style={{"max-width":"600px","margin":"40px auto"}}><div {...stylex.props(s.kicker)}>MAGIC LINK</div><h1>Sign in to VutaDex</h1><Show when={!sent()} fallback={<p>Check your email. The link expires in 10 minutes.</p>}><form {...stylex.props(s.form)} onSubmit={submit}><input {...stylex.props(s.input)} type="email" required placeholder="you@example.com" value={email()} onInput={e=>setEmail(e.currentTarget.value)}/><button {...stylex.props(s.button)}>Send link</button></form></Show></div></main></>}
function Verify(){const[params]=useSearchParams();const nav=useNavigate();const[error,setError]=createSignal("");async function verify(){try{await api.verify(String(params.token??""));nav("/")}catch(e){setError(e instanceof Error?e.message:"Verification failed")}}return <><Nav/><main {...stylex.props(s.section)}><div {...stylex.props(s.card)} style={{"max-width":"600px","margin":"40px auto"}}><div {...stylex.props(s.kicker)}>CONFIRM SIGN-IN</div><h1>Finish signing in</h1><p {...stylex.props(s.muted)}>For safety, the email link does not consume itself until you confirm here.</p><button {...stylex.props(s.button)} onClick={verify}>Confirm sign-in</button><Show when={error()}><p style={{color:colors.danger}}>{error()}</p></Show></div></main></>}
function formatClock(s:number){return `${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`}
