import * as stylex from "@stylexjs/stylex";

export const colors = stylex.defineVars({
  bg: "#07110b",
  panel: "#0d1b12",
  panel2: "#13281a",
  line: "#24482e",
  text: "#effff3",
  muted: "#92aa98",
  green: "#17ff7a",
  gold: "#ffd166",
  danger: "#ff6577",
});

export const s = stylex.create({
  global: { minHeight: "100vh", backgroundColor: colors.bg, color: colors.text, fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif" },
  nav: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "18px 24px", borderBottom: "1px solid", borderColor: colors.line, position: "sticky", top: 0, backgroundColor: colors.bg, zIndex: 10 },
  brand: { fontSize: "18px", fontWeight: 900, letterSpacing: "0.18em", color: colors.green, textDecoration: "none" },
  links: { display: "flex", gap: "18px", alignItems: "center" },
  link: { color: colors.muted, textDecoration: "none", fontWeight: 700 },
  hero: { maxWidth: "1160px", margin: "0 auto", padding: "88px 24px 42px", display: "grid", gridTemplateColumns: { default: "minmax(0,1.05fr) minmax(320px,.95fr)", "@media (max-width: 850px)": "1fr" }, gap: "48px", alignItems: "center" },
  kicker: { color: colors.green, fontWeight: 900, letterSpacing: ".14em", fontSize: "12px" },
  h1: { fontSize: "clamp(48px,8vw,94px)", lineHeight: .92, letterSpacing: "-.055em", margin: "16px 0 22px" },
  lead: { fontSize: "20px", lineHeight: 1.55, color: colors.muted, maxWidth: "650px" },
  actions: { display: "flex", gap: "12px", marginTop: "30px", flexWrap: "wrap" },
  button: { appearance: "none", border: "1px solid", borderColor: colors.green, backgroundColor: colors.green, color: "#021407", padding: "12px 18px", borderRadius: "10px", fontWeight: 900, cursor: "pointer", textDecoration: "none" },
  ghost: { backgroundColor: "transparent", color: colors.green },
  card: { backgroundColor: colors.panel, border: "1px solid", borderColor: colors.line, borderRadius: "18px", padding: "20px" },
  field: { position: "relative", height: "430px", borderRadius: "16px", overflow: "hidden", backgroundColor: "#123d20", border: "1px solid", borderColor: "#2d7041" },
  yard: { position: "absolute", left: 0, right: 0, height: "1px", backgroundColor: "rgba(255,255,255,.16)" },
  token: { position: "absolute", width: "34px", height: "34px", borderRadius: "50%", display: "grid", placeItems: "center", fontWeight: 900, border: "2px solid white", transform: "translate(-50%,-50%)" },
  x: { backgroundColor: "#0b7bff" },
  o: { backgroundColor: "#ff3b52" },
  shell: { maxWidth: "1300px", margin: "0 auto", padding: "24px" },
  score: { display: "grid", gridTemplateColumns: "1fr auto 1fr", gap: "18px", alignItems: "center", marginBottom: "16px" },
  team: { fontSize: "22px", fontWeight: 900 },
  center: { textAlign: "center" },
  muted: { color: colors.muted },
  grid: { display: "grid", gridTemplateColumns: { default: "minmax(0,1fr) 360px", "@media (max-width: 900px)": "1fr" }, gap: "18px" },
  feed: { maxHeight: "430px", overflow: "auto", display: "flex", flexDirection: "column", gap: "10px" },
  play: { paddingBottom: "10px", borderBottom: "1px solid", borderColor: colors.line },
  form: { display: "flex", gap: "10px", maxWidth: "520px", marginTop: "18px" },
  input: { flex: 1, backgroundColor: colors.panel, border: "1px solid", borderColor: colors.line, borderRadius: "10px", padding: "12px", color: colors.text },
  section: { maxWidth: "1160px", margin: "0 auto", padding: "48px 24px" },
  three: { display: "grid", gridTemplateColumns: { default: "repeat(3,1fr)", "@media (max-width: 760px)": "1fr" }, gap: "16px" },
});
